services:
  lowbudget-client:
    image: lowbudget-client
    container_name: lowbudget-client 
    ports:
      - "3000:3000"

  lowbudget-server:
    image: lowbudget-server
    container_name: lowbudget-server 
    env_file: server/.env
