services:
  client:
    image: lblcs-client
    container_name: lblcs-client-container
    ports:
      - "3000:80"

  server:
    image: lblcs-server
    container_name: lblcs-server-container
    env_file: server/.env
    ports:
      - "3001:8080"
