import { DraftProps } from "./interfaces/draftInterfaces";

export const defaultDraftState: DraftProps = {
    draftStarted: false,
    activePhase: null,
    phaseType: null,
    blueDisplayName: "Blue Team",
    redDisplayName: "Red Team",
    blueReady: false,
    redReady: false,
    timer: 34,
    bansArray: [],
    picksArray: [],
    bluePicks: [],
    redPicks: [],
    blueBans: [],
    redBans: [],
    banIndex: 0,
    pickIndex: 0,
    currentTurn: "",
    currentBluePick: 0,
    currentRedPick: 0,
    currentBlueBan: 0,
    currentRedBan: 0,
    displayTurn: null,
    currentHover: null,
    bluePick: "nothing",
    redPick: "nothing",
    draftComplete: false,
    fearlessCode: null
  }